version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ts-backend
    ports:
      - "4200:4200"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=language_course
      - DEV_ENVIRONMENT=true
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
